version: 2
project_name: bonsai
builds:
  - id: bonsai
    main: .
    binary: bonsai
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/Tiago-0liveira/bonsai/internal/version.Version={{.Version}} -X github.com/Tiago-0liveira/bonsai/internal/version.Commit={{.Commit}} -X github.com/Tiago-0liveira/bonsai/internal/version.Date={{.Date}}
archives:
  - formats: [tar.gz]
    name_template: 'bonsai_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - bcd.bat
checksum:
  name_template: checksums.txt
  algorithm: sha256
release:
  github:
    owner: Tiago-0liveira
    name: bonsai
  draft: true
changelog:
  sort: asc
