import { expect, test } from '@playwright/test'
import { openConnectedApp } from './mockGit'

test.skip(!['linux', 'darwin'].includes(process.platform), 'Native Unix PTY fixture')

test('real API and PTY: profile launch, input, reload, stop and retained output', async ({ page }) => {
  await openConnectedApp(page)
  await page.keyboard.press('Control+k')
  await page.getByRole('option', { name: 'Start agent', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Start agent' })
  await expect(dialog.getByRole('button', { name: /Claude/ })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: /Codex/ })).toBeDisabled()
  await expect(dialog.getByLabel('Profile')).toContainText('Fixture')
  await dialog.getByLabel('Worktree and branch').click()
  await page.getByRole('option').first().click()
  const startResponse = page.waitForResponse(r => r.request().method() === 'POST' && r.url().endsWith('/api/projects/repo/agents'))
  await dialog.getByRole('button', { name: 'Start agent', exact: true }).click()
  const session = await (await startResponse).json()
  await expect(page.locator('.xterm')).toBeVisible()
  await expect(page.locator('.runtime-tile')).toContainText('running · connected')
  await page.locator('.xterm-helper-textarea').pressSequentially('browser-input')
  await page.locator('.xterm-helper-textarea').press('Enter')
  await expect(page.locator('.xterm-screen')).toContainText('REPLY:browser-input')
  await page.getByRole('button', { name: 'Close runtime card' }).click()
  await expect(page.locator('.xterm')).toHaveCount(0)
  await page.getByRole('button', { name: 'Open runtime', exact: true }).click()
  await page.getByRole('option', { name: /Fixture/ }).click()
  await expect(page.locator('.runtime-tile')).toContainText('running · connected')
  await expect(page.locator('.xterm-screen')).toContainText('REPLY:browser-input')
  await page.setViewportSize({ width: 1250, height: 850 })
  await page.reload()
  await page.getByRole('button', { name: 'Connect to local Bonsai' }).click()
  await expect(page.getByTestId(`rf__node-${session.id}`)).toBeVisible()
  await page.getByTestId(`rf__node-${session.id}`).click()
  await expect(page.locator('.runtime-tile')).toContainText('running · connected')
  await expect(page.locator('.xterm-screen')).toContainText('REPLY:browser-input')
  await page.getByRole('button', { name: 'Stop agent', exact: true }).first().click()
  await expect(page.locator('.runtime-tile')).toContainText('exited')
})
