import { expect, test } from '@playwright/test'
import { openConnectedApp } from './mockGit'

test.skip(!['linux', 'darwin'].includes(process.platform), 'Native Unix PTY fixture')

test('real API and PTY: profile launch, input, reload, stop and retained output', async ({ page }) => {
  await openConnectedApp(page)
  await page.keyboard.press('Control+k')
  await page.getByRole('option', { name: 'Start agent', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Start agent' })
  await expect(dialog.getByRole('button', { name: /Claude/ })).toBeEnabled()
  await expect(dialog.getByRole('button', { name: /Codex/ })).toBeDisabled()
  await dialog.getByRole('button', { name: /Antigravity/ }).click()
  await expect(dialog.getByLabel('Profile')).toContainText('Fixture')
  await dialog.getByLabel('Worktree and branch').click()
  await page.getByRole('option').first().click()
  const startResponse = page.waitForResponse(r => r.request().method() === 'POST' && r.url().endsWith('/api/projects/repo/agents'))
  await dialog.getByRole('button', { name: 'Start agent', exact: true }).click()
  const session = await (await startResponse).json()
  await expect(page.locator('.xterm')).toBeVisible()
  await expect(page.locator('.runtime-tile')).toContainText('running · connected')
  await page.locator('.xterm-helper-textarea').pressSequentially('browser-input')
  await page.locator('.xterm-helper-textarea').press('Enter')
  await expect(page.locator('.xterm-screen')).toContainText('REPLY:browser-input')
  await page.getByRole('button', { name: 'Close runtime card', exact: true }).click()
  await expect(page.locator('.xterm')).toHaveCount(0)
  await page.getByRole('button', { name: 'Open runtime', exact: true }).click()
  await page.getByRole('option', { name: /Fixture/ }).click()
  await expect(page.locator('.runtime-tile')).toContainText('running · connected')
  await expect(page.locator('.xterm-screen')).toContainText('REPLY:browser-input')
  await page.setViewportSize({ width: 1250, height: 850 })
  await page.reload()
  await page.getByRole('button', { name: 'Connect to local Bonsai' }).click()
  await expect(page.getByTestId(`rf__node-${session.id}`)).toBeVisible()
  await page.getByTestId(`rf__node-${session.id}`).click()
  await expect(page.locator('.runtime-tile')).toContainText('running · connected')
  await expect(page.locator('.xterm-screen')).toContainText('REPLY:browser-input')
  await page.getByRole('button', { name: 'Stop agent', exact: true }).first().click()
  await expect(page.locator('.runtime-tile')).toContainText('exited')
})

test('real API and PTY: two concurrent sessions of one Claude profile, reload and stop one', async ({ page }) => {
  await openConnectedApp(page)
  const start = async (name: string) => {
    await page.keyboard.press('Control+k')
    await page.getByRole('option', { name: 'Start agent', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Start agent' })
    await dialog.getByRole('button', { name: /Claude/ }).click()
    await expect(dialog.getByLabel('Profile')).toContainText('Work')
    await dialog.getByLabel('Worktree and branch').click()
    await page.getByRole('option').first().click()
    await dialog.getByLabel('Agent name').fill(name)
    await dialog.getByLabel('Agent model').click()
    await expect(page.getByRole('option', { name: /^Opus/ })).toBeVisible()
    await expect(page.getByRole('option', { name: /^Fable/ })).toBeVisible()
    await page.getByRole('option', { name: /^Sonnet/ }).click()
    await expect(dialog.getByLabel('Agent model')).toHaveValue('sonnet')
    await dialog.getByLabel('Permission mode').click()
    await page.getByRole('option', { name: 'Plan', exact: true }).click()
    const response = page.waitForResponse(r => r.request().method() === 'POST' && r.url().endsWith('/api/projects/repo/agents'))
    await dialog.getByRole('button', { name: 'Start agent', exact: true }).click()
    const session = await (await response).json()
    expect(session).toMatchObject({ provider: 'claude', profile_name: 'Work' })
    return session.id as string
  }
  const tile = (name: string) => page.locator('.runtime-tile').filter({ hasText: name })
  const type = async (name: string, text: string) => {
    const input = tile(name).locator('.xterm-helper-textarea')
    await input.pressSequentially(text)
    await input.press('Enter')
  }

  const first = await start('alpha')
  await expect(tile('alpha').locator('.xterm-screen')).toContainText('READY')
  const second = await start('beta')
  expect(second).not.toBe(first)
  await expect(tile('beta').locator('.xterm-screen')).toContainText('READY')
  await type('alpha', 'to-alpha')
  await type('beta', 'to-beta')
  await expect(tile('alpha').locator('.xterm-screen')).toContainText('REPLY:to-alpha')
  await expect(tile('beta').locator('.xterm-screen')).toContainText('REPLY:to-beta')
  await expect(tile('alpha').locator('.xterm-screen')).not.toContainText('REPLY:to-beta')
  await expect(tile('beta').locator('.xterm-screen')).not.toContainText('REPLY:to-alpha')

  await page.setViewportSize({ width: 1250, height: 850 })
  await page.reload()
  await page.getByRole('button', { name: 'Connect to local Bonsai' }).click()
  await expect(page.getByTestId(`rf__node-${first}`)).toBeVisible()
  await expect(page.getByTestId(`rf__node-${second}`)).toBeVisible()
  await page.getByTestId(`rf__node-${first}`).click()
  await expect(tile('alpha').locator('.xterm-screen')).toContainText('REPLY:to-alpha')

  await tile('alpha').getByRole('button', { name: 'Stop agent', exact: true }).click()
  await expect(tile('alpha')).toContainText('exited')
  await page.getByTestId(`rf__node-${second}`).click()
  await expect(tile('beta')).toContainText('running · connected')
  await type('beta', 'still-alive')
  await expect(tile('beta').locator('.xterm-screen')).toContainText('REPLY:still-alive')
})
