import { expect, test } from '@playwright/test'
import { mockGitBackend, openConnectedApp } from './mockGit'
import { waitForViewportToSettle } from './viewport'

test('remote branch creation and canonical state add and remove the node', async ({ page }) => {
  await mockGitBackend(page, false, false, true)
  await openConnectedApp(page)
  await waitForViewportToSettle(page)
  const viewport = () => page.locator('.react-flow__viewport').getAttribute('style')
  const placements = () => page.evaluate(() => JSON.parse(localStorage.getItem('bonsai-web-workspace-v6')!).state.nodePlacements)
  const beforeViewport = await viewport()
  const beforePlacements = await placements()
  await page.getByRole('button', { name: 'New worktree' }).click()
  const dialog = page.getByRole('dialog', { name: 'New worktree' })
  await dialog.getByRole('button', { name: /Remote branch/ }).first().click()
  await expect(dialog.getByRole('button', { name: 'Remote branch', exact: true })).toHaveText('origin/discovered')
  const request = page.waitForRequest(request => request.method() === 'POST' && request.url().endsWith('/api/projects/bonsai/worktrees'))
  await dialog.getByRole('button', { name: 'Create worktree' }).click()
  expect((await request).postDataJSON()).toMatchObject({ mode: 'remote', branch: 'discovered', base: 'origin/discovered' })
  await expect(dialog).toHaveCount(0)
  const created = page.getByTestId('rf__node-wt-created')
  await expect(created).toHaveCount(1)
  await expect(page.getByRole('heading', { name: 'discovered' })).toBeVisible()
  expect(await viewport()).toBe(beforeViewport)
  const afterCreation = await placements()
  for (const [id, placement] of Object.entries(beforePlacements)) expect(afterCreation[id]).toEqual(placement)
  await page.getByRole('button', { name: 'Delete worktree', exact: true }).click()
  const remove = page.getByRole('dialog', { name: 'Delete worktree' })
  await expect(remove).toContainText('/trees/discovered')
  await remove.getByRole('button', { name: 'Delete worktree', exact: true }).click()
  await expect(created).toHaveCount(0)
  expect(await viewport()).toBe(beforeViewport)
  const afterDeletion = await placements()
  for (const [id, placement] of Object.entries(beforePlacements)) expect(afterDeletion[id]).toEqual(placement)
})

test('automatic unlinked stack shows reasons and dirty deletion requires discard', async ({ page }) => {
  const fixture = await mockGitBackend(page, false, false, true)
  await openConnectedApp(page)
  const stack = page.getByTestId('rf__node-stack:unlinked:bonsai')
  await expect(stack).toContainText('Local / unlinked')
  await expect(stack.getByText(/No upstream/)).toHaveCount(2)
  await waitForViewportToSettle(page)
  const unrelated = page.getByTestId('rf__node-wt-release')
  const before = await unrelated.boundingBox()
  const beforeViewport = await page.locator('.react-flow__viewport').getAttribute('style')
  await stack.getByRole('button', { name: 'local/one', exact: false }).first().click()
  await page.getByRole('button', { name: 'Delete worktree', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Delete worktree' })
  await expect(dialog.getByRole('button', { name: 'Delete worktree', exact: true })).toBeDisabled()
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button', { name: 'Delete worktree', exact: true }).click()
  await expect(stack).toHaveCount(0)
  await expect(page.getByTestId('rf__node-wt-local-one')).toHaveCount(0)
  await expect(page.getByTestId('rf__node-wt-local-two')).toHaveCount(1)
  expect(await unrelated.boundingBox()).toEqual(before)
  expect(await page.locator('.react-flow__viewport').getAttribute('style')).toBe(beforeViewport)
  fixture.publish()
  await expect(page.getByTestId('rf__node-wt-local-two')).toHaveCount(1)
  expect(await unrelated.boundingBox()).toEqual(before)
})

test('automatic group expansion preserves unrelated nodes and viewport', async ({ page }) => {
  await mockGitBackend(page, false, false, true)
  await openConnectedApp(page)
  await waitForViewportToSettle(page)
  const baseline = () => page.evaluate(() => {
    const state = JSON.parse(localStorage.getItem('bonsai-web-workspace-v6')!).state
    return { placement: state.nodePlacements['wt-release'], viewport: document.querySelector('.react-flow__viewport')?.getAttribute('style') }
  })
  const before = await baseline()
  await page.getByTestId('rf__node-stack:unlinked:bonsai').getByRole('button', { name: /Expand/ }).click()
  await expect(page.getByTestId('rf__node-wt-local-one')).toHaveCount(1)
  await expect(page.getByTestId('rf__node-wt-local-two')).toHaveCount(1)
  expect(await baseline()).toEqual(before)
})
